### ISSUE TITLE
cmor file not created from high frequency var

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#127]
Hi all,
please forgive me if this is a trivial issue but I am not able to see the solution by myself: I am trying to cmorize some PRIMAVERA data with the PRIMAVERA tables: first question, is anyone still using this? Should I use the PRIMAVERA branch (where there are no PRIMAVERA tables)?

Back to my problem: I have noticed that with PRIMAVERA tables I only obtain daily and monthly cmor data. All the high frequency postprocessed data (3hr, 3hrPt, 6hr, 6hrPt) does not show up. 

For example, if I have a very simple _varlist.json_ test file, i.e.

`{
    "Prim3hr": [
        "sfcWind",
        "evspsbl",
        "sfcWindmax"
    ]
}`

when I run the cmorization, Prim3hr data are not created and this is the log I get: apparently there is an error but it not clear where this is coming from.

```
INFO:taskloader:Found 3 cmor target variables in input variable list.
INFO:taskloader:Created 3 ece2cmor tasks from input variable list.
INFO:ece2cmorlib:Selected 3 IFS tasks from 3 input tasks
INFO:ifs2cmor:Inspecting 3 tasks.
INFO:ifs2cmor:Validated 3 tasks for processing.
INFO:ifs2cmor:Executing 3 IFS tasks...
INFO:ifs2cmor:Post-processing mask variables...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Post-processing surface pressures...
INFO:ifs2cmor:Post-processing 0 IFS tasks...
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing surface pressures...
INFO:ifs2cmor:Cmorizing 0 IFS tasks...
INFO:ifs2cmor:Post-processing regular variables...
INFO:ifs2cmor:Post-processing 3 IFS tasks...
ERROR:postproc:Unsupported combination of frequency 3hr with time operators [u'mean'] encountered
ERROR:postproc:Unsupported combination of frequency 3hr with time operators [u'mean'] encountered
ERROR:postproc:Unsupported combination of frequency 3hr with time operators [u'maximum'] encountered
INFO:postproc:Post-processing target sfcWind in table Prim3hr from file /marconi_scratch/userexternal/pdavini0/tmp_cmor/sta1_30928/tmp_1951_1/filtered/3hr/ICMGGsta1+195101 with cdo command -expr,'var214=sqrt(sqr(var165)+sqr(var166))' -setgridtype,regular -selcode,165,166
ERROR:cmor_task:Attempt to increase failed status for task ignored
INFO:postproc:Post-processing target sfcWindmax in table Prim3hr from file /marconi_scratch/userexternal/pdavini0/tmp_cmor/sta1_30928/tmp_1951_1/filtered/3hr/ICMGGsta1+195101 with cdo command -expr,'var214=sqrt(sqr(var165)+sqr(var166))' -setgridtype,regular -selcode,165,166
ERROR:cmor_task:Attempt to increase failed status for task ignored
INFO:postproc:Post-processing target evspsbl in table Prim3hr from file /marconi_scratch/userexternal/pdavini0/tmp_cmor/sta1_30928/tmp_1951_1/filtered/3hr/ICMGGsta1+195101 with cdo command -setgridtype,regular -selcode,182
ERROR:cmor_task:Attempt to increase failed status for task ignored
INFO:ifs2cmor:Post-processed batch of 0 tasks.
INFO:ifs2cmor:Cmorizing regular variables...
INFO:ifs2cmor:Cmorizing 0 IFS tasks...

! ------
! All files were closed successfully. 
! ------
```

Is there any way to increase the verbosity? I am running with python 2.7.12 and cdo 1.8.2, which is a pretty standard configuration I think. The weirdest thing is that if I run for example 

`cdo expr,'var214=sqrt(sqr(var165)+sqr(var166))' -setgridtype,regular -selcode,165,166`

it runs smooth and a grib file is created. What I am doing wrong? 
Any suggestions welcome!
Cheers,
Paolo

**Comment by goord** [comment]
The problem is that in your version of the tables the high frequency variables are denoted with the mean operators which ece2cmor3 does not accept. I have fixed this in the nocdo branch but it is not yet merged. One way would be to edit the tables and replace 'mean' with 'point' for these. I am currently not able to fix it in the code because I am on vacation.

**Comment by oloapinivad** [comment]
Thanks for the prompt reply (especially since you are on vacation). This is a very good hint! 
I modified this for the two mean variables (I let the maximum one as it is for the moment) but it crashes again blaming time bounds. Is there any official repository for the Primavera tables repository? Perhaps I am using a wrong version.
Best,
Paolo

```
C Traceback:
In function: cmor_set_var_def_att
! called from: cmor_set_variable_entry
! called from: cmor_load_table_internal
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Table Prim3hr, unknown variable attribute: >>>>primavera_priority<<<< value: (1)
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_set_var_def_att
! called from: cmor_set_variable_entry
! called from: cmor_load_table_internal
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Table Prim3hr, unknown variable attribute: >>>>primavera_priority<<<< value: (1)
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
In function: cmor_set_var_def_att
! called from: cmor_set_variable_entry
! called from: cmor_load_table_internal
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Table Prim3hr, unknown variable attribute: >>>>primavera_priority<<<< value: (1)
!
!!!!!!!!!!!!!!!!!!!!!!!!!

INFO:ifs2cmor:Creating time axes for table Prim3hr...
INFO:ifs2cmor:Creating time axis using variable sfcWind...

C Traceback:
! In function: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis: time (table: Prim3hr) must have bounds, you did not pass any when creating it via cmor_axis
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ece2cmor.py", line 75, in <module>
    main()
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ece2cmor.py", line 68, in main
    maxsizegb = args.tmpsize)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 139, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks,cleanup = cleanup)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ifs2cmor.py", line 132, in execute
    cmorize(processedtasks)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ifs2cmor.py", line 344, in cmorize
    create_time_axes(tskgroup)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ifs2cmor.py", line 458, in create_time_axes
    tid = create_time_axis(freq = task.target.frequency,path = getattr(task,"path"),name = tdim,hasbnds = (timop != ["point"]))
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ifs2cmor.py", line 624, in create_time_axis
    return cmor.axis(table_entry = str(name),units = "hours since " + str(ref_date_),coord_vals = times)
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/cmor/pywrapper.py", line 444, in axis
    type, cell_bounds, cbnds, interval)
_cmor.CMORError: Problem with 'cmor.axis'. Please check the logfile (if defined).
```

**Comment by goord** [comment]
Ok that's an issue from our side. Can you try the primavera branch of ece2cmor3? After switching remember to type git submodule update --init --recursive to checkout the primavera tables of John seddon

**Comment by oloapinivad** [comment]
Thanks. I tried this way right now, but apparently there is no _PRIMAVERA_grids.json_ in the Jon Seddon tables, which leads to a crash of the code.

**Comment by goord** [comment]
Hi sorry for my late answer. I have had this issue too and solved it my creating symlink to CMIP6_grids.json named PRIMAVERA_grids.json or a copy will do as well.

**Comment by oloapinivad** [comment]
Following the discussion at #146, I think this is deprecated.
