### ISSUE TITLE
NEMO crash with siconc: zaxid = depth_axes_[tableid][grid_index]

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#128]
Hi all,

I am getting this repeated error when I try to cmorize NEMO output, no difference if this is high resolution or low resolution. Did anyone ever spotted something similar? 
Unfortunately, this is occurring with any tables or varlists.  

```
IINFO:taskloader:Found 210 cmor target variables in input variable list.
INFO:taskloader:Created 17 ece2cmor tasks from input variable list.
INFO:ece2cmorlib:Selected 16 NEMO tasks from 17 input tasks
===============================================================
KJS EDIT. Printing all keys associated to this netcdf file:
[u'nav_lat', u'nav_lon', u'ncatice', u'siu', u'time_centered', u'time_centered_bounds', u'time_counter', u'time_counter_bounds', u'siv', u'siconc', u'sithick', u'sivol', u'sisnthick', u'sitemptop', u'sispeed', u'alb_ice', u'sicompstren', u'siage', u'siflswdtop', u'sistrxdtop', u'sistrydtop', u'prsn', u'sidmassevapsubl', u'sidivvel', u'siitdconc', u'siitdthick', u'siitdsnthick', u'sisali', u'sivolu', u'snvolu', u'vfxice', u'vfxsnw', u'vfxsub', u'vfxsub_err', u'vfxspr', u'sivtrp', u'snvtrp', u'saltrp', u'deitrp', u'destrp', u'sfx', u'hfxout', u'hfxin', u'sst', u'sss', u'sitemp', u'siheco', u'snheco', u'sishea', u'sibrin', u'sicolf', u'siagecat', u'salincat', u'sibricat', u'sitemcat', u'sntemcat']
Now trying to access time_centered variable...
===============================================================
INFO:nemo2cmor:Creating NEMO grids in CMOR...
INFO:nemo2cmor:Executing 16 NEMO tasks...
INFO:nemo2cmor:Cmorizing NEMO tasks...
INFO:nemo2cmor:Loading CMOR table SImon to process 16 variables...
INFO:nemo2cmor:Creating time axes for table SImon...
INFO:nemo2cmor:Creating depth axes for table SImon...
INFO:nemo2cmor:Cmorizing source variable siconc to target variable siconc...
ERROR:nemo2cmor:Depth axis for grid icemod has not been created; skipping variable.
Traceback (most recent call last):
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ece2cmor.py", line 75, in <module>
    main()
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ece2cmor.py", line 70, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir,args.exp,startdate,length)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 151, in perform_nemo_tasks
    nemo2cmor.execute(nemo_tasks)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/nemo2cmor.py", line 102, in execute
    execute_netcdf_task(task,ds,tab_id)
  File "/marconi_work/Pra13_3311/ecearth3/post/ece2cmor3/ece2cmor3/ece2cmor3/nemo2cmor.py", line 128, in execute_netcdf_task
    zaxid = depth_axes_[tableid][grid_index]
KeyError: 4

```

**Comment by goord** [comment]
Apparently it does not create a vertical axis for the icemod file. I will have a look at it when I get back from holidays, 7 the of march

**Comment by oloapinivad** [comment]
Thanks @goord. 
For now, I am able to circumvent this issue removing variable **siconc** from  _varlist.json_
Later on, I had to remove **sidivvel**
In this way the scripts goes on and produce almost all the other variables. However, sea ice concentration is a pretty much important variable so I guess we should try to solve this depth axis issue.

**Comment by goord** [comment]
The problem was that the new data request added a 'sea ice type' dimension to siconc which was mistakingly interpreted as a depth axis by ece2cmor3. This should be fixed after the latest commit 3d88cd7f2514c7ceb4620fc00fd6f346b2c5af63

**Comment by oloapinivad** [comment]
Great, this is working, thanks a lot. 

I found out that an extra issue in **sidivvel**, but this was a mistake in the SImon table where the time dimensions was time1 instead of time. To whom I should report this?
Thanks

**Comment by oloapinivad** [comment]
Still having some issue with siddivel, but the main issue is resolved. I will open a single issue for all the problems I am having combining master branch with PRIMAVERA tables.
