### ISSUE TITLE
Attribute error with --filter option

### ISSUE THREAD

**Issue by oloapinivad** [goord/ece2cmor3#132]
Hi all,

I am trying the --filter option that, as long as I understand, should take care of the filtering for PRIMAVERA output automatically.  However, the code crashes pretty soon. The command I run is (I removed the fullpath to increase readability)
````
ece2cmor.py filtered 2002-01-01 --exp qsh0 --conf metadata-qsh0-leg000.json
 --vars varlist-cmip6.json --npp 1 --tmpdir CMIP6 --tabid CMIP6 
--mode append --atm --filter
````

Here below the log I get, any suggestion is welcome!
Thanks,
Paolo

````
INFO:ece2cmor3.taskloader:Found 210 cmor target variables in input variable list.
INFO:ece2cmor3.taskloader:Created 194 ece2cmor tasks from input variable list.
INFO:ece2cmor3.ece2cmorlib:Selected 194 IFS tasks from 194 input tasks
INFO:ece2cmor3.grib_filter:Searching for previous month file of /marconi_scratch/userexternal/pdavini0/tmp_cmor/qsh0_3946/tmp_2002_1/filtered/ICMGGqsh0+200201
INFO:ece2cmor3.ifs2cmor:Inspecting 194 tasks.
INFO:ece2cmor3.ifs2cmor:Validated 194 tasks for processing.
INFO:ece2cmor3.ifs2cmor:Executing 194 IFS tasks...
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 139.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 248.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 246.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 247.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 157.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 129.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 157.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 248.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 246.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 247.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 54.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 170.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 139.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 139.128, level type 1, level 0
Traceback (most recent call last):
  File "/marconi_work/Pra13_3311/ecearth3/PRIMAVERA/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 76, in <module>
    main()
  File "/marconi_work/Pra13_3311/ecearth3/PRIMAVERA/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 69, in main
    maxsizegb = args.tmpsize)
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 153, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks,cleanup = cleanup)
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ifs2cmor.py", line 110, in execute
    tasks_todo = grib_filter.execute(tasks_todo, start_date_.month)
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/grib_filter.py", line 204, in execute
    proc_mon(month, path, prev_path, filehandles)
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/grib_filter.py", line 279, in proc_mon
    proc_prev_month(month, grib_file.create_grib_file(fin), handles)
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/grib_filter.py", line 350, in proc_prev_month
    code = grib_tuple_from_string(gribfile.get_field(grib_file.param_key))
  File "/marconi_work/Pra13_3311/opt/anaconda/envs/ece2cmor3/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/grib_filter.py", line 53, in grib_tuple_from_string
    codes = s.split('.')
AttributeError: 'int' object has no attribute 'split'
```

**Comment by goord** [comment]
Hi Paolo, this is a bug you discovered, I will fix it asap.

**Comment by goord** [comment]
Ok, this should fixed after 51520a51231a07cafc8447e80cedb9bf80dbf924

**Comment by oloapinivad** [comment]
Hi @goord thanks a lot.
I have pulled the last version

````commit 51520a51231a07cafc8447e80cedb9bf80dbf924
Author: gvdoord <g.vandenOord@gmail.com>
Date:   Thu Mar 8 17:16:42 2018 +0100

    Fixed bug in previous month processing

diff --git a/ece2cmor3/grib_filter.py b/ece2cmor3/grib_filter.py
index ea11b15..583ed1b 100644
--- a/ece2cmor3/grib_filter.py
+++ b/ece2cmor3/grib_filter.py
@@ -347,7 +347,7 @@ def write_record(gribfile, shift=0, handles=None):
 def proc_prev_month(month, gribfile, handles):
     while gribfile.read_next():
         if get_mon(gribfile) == month:
-            code = grib_tuple_from_string(gribfile.get_field(grib_file.param_key))
+            code = grib_tuple_from_int(gribfile.get_field(grib_file.param_key))
             if code not in accum_codes:
                 write_record(gribfile, handles=handles)
         gribfile.release()
````

But I am getting the same error as before:

````
AttributeError:` 'int' object has no attribute 'split'
````

Also I am noticing that 

````
INFO:ece2cmor3.grib_filter:Searching for previous month file of /marconi_scratch/userexternal/pdavini0/tmp_cmor/qsh0_14079/tmp_2002_2/filtered/ICMGGqsh0+200201
````

In the previous filtering, it was possible to specify the path of the previous month file: is it possible to do it now?

Thanks a lot

**Comment by goord** [comment]
Hi Paolo, did you run ```python setup.py install``` again? If the problem persists after that, can you post the full backtrace?

The program looks for the previous month file automatically, both in the current dir and recursively one directory up (so it should find it if it is in the previous leg). Does it print that it didn't find this file? Otherwise it's been found and everything is fine.

**Comment by oloapinivad** [comment]
Hi @goord, sorry for my silence but it was my turn on vacation ;-)
It was my fault, I was not aware of that I need to reinstall it. Now it seems working fine.
Re. the previous month, I solved linking the files I need to a new folder (at CNR we use a different directory tree which was not compatible to the original script). 

Now the code is crashing in another instance with var `hfdsn_LImon.nc,` I will open a differenti issue if the problem persists!
Thanks for the help

**Comment by oloapinivad** [comment]
Sorry but I need to reopen it. 

I am getting plenty of variables at high frequency, both instanteneous and cumulated so I think that filtering is working fine. 

However, I am getting this series of errors in the logfile. What is strange is that they many of them, as 40.128 or 139.128 are present in the "previous" month file. 
So it seems that the filtering is not able to read it. I have noticed that this error is related often to soil variables, indeed var `mrsos` is missing at every frequency (which is based on var 39.128 and 40.128, and they are both present in my previous and present month file).
Could it be possible that there is some mismatch on the vertical grid on which they are searched?

`````
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 139.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 248.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 246.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 247.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 157.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 129.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 157.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 248.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 246.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 247.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 54.128, level type 109, level -1
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 170.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 40.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 139.128, level type 1, level 0
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 139.128, level type 1, level 0
`````

**Comment by goord** [comment]
Yes I have also noticed these error messages, I will have a look at it today.

**Comment by oloapinivad** [comment]
Hi @goord,
thanks a lot, I have seen you fixed in a recent commit. I tested it and I am getting soil variable, great.
However, continuing my debugging - sorry for that - I have still a few variables not correctly recognized: 

`````
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 248.128, level type 109, level -1. Dismissing task cl in table Amon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 246.128, level type 109, level -1. Dismissing task clw in table Amon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 247.128, level type 109, level -1. Dismissing task cli in table Amon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1. Dismissing task ta in table CFmon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 157.128, level type 109, level -1. Dismissing task hur in table CFmon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 109, level -1. Dismissing task hus in table CFmon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1. Dismissing task wap in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1. Dismissing task u2 in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1. Dismissing task v2 in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1. Dismissing task wap2 in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1. Dismissing task t2 in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1. Dismissing task uv in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1. Dismissing task uwap in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1. Dismissing task vwap in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1. Dismissing task ut in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1. Dismissing task vt in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1. Dismissing task twap in table Emon
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 131.128, level type 109, level -1. Dismissing task ua in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 132.128, level type 109, level -1. Dismissing task va in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 130.128, level type 109, level -1. Dismissing task ta in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 133.128, level type 109, level -1. Dismissing task hus in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 135.128, level type 109, level -1. Dismissing task wap in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 129.128, level type 109, level -1. Dismissing task zg in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 157.128, level type 109, level -1. Dismissing task hur in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 248.128, level type 109, level -1. Dismissing task cl in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 246.128, level type 109, level -1. Dismissing task clw in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 247.128, level type 109, level -1. Dismissing task cli in table CFday
ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 54.128, level type 109, level -1. Dismissing task pfull in table CFday
`````

As long as I understand, all these are requests on the hybrid levels (alevel).  These have not been saved in our simulations, so it makes sense that they are missing. 
If you can confirm I can now finally close the issue.
Thanks again.

**Comment by goord** [comment]
Hi Paolo, if you haven't got these fields on model levels in your output, it is intended that ece2cmor3 notifies you. If you want to get rid of these messages, you can remove the corresponding variables from your request varlist

**Comment by oloapinivad** [comment]
Thanks for the clarification. I can close the issue then!
Best,
Paolo
