### ISSUE TITLE
Error: local variable 'temp_dir_' referenced before assignment

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#15]
When running `prim_atm_6hr.py` I get:
<pre>
Traceback (most recent call last):
  File "./prim_atm_6hr.py", line 62, in <module>
    main(sys.argv[1:])
  File "./prim_atm_6hr.py", line 59, in main
    ece2cmor.perform_ifs_tasks(outputfreq = 6,tempdir = opt.temp,maxsizegb = 128,taskthreads = 16)
  File "/home/sm_wyser/ece2cmor3/testing/ece2cmor.py", line 85, in perform_ifs_tasks
    ifs2cmor.cleanup(ifs_tasks)
  File "/home/sm_wyser/ece2cmor3/testing/ifs2cmor.py", line 120, in cleanup
    if(cleanupdir and tempdir_created_ and len(os.listdir(temp_dir_)) == 0):
UnboundLocalError: local variable 'temp_dir_' referenced before assignment
</pre>

**Comment by klauswyser** [comment]
The error disappears automagically when I run ./prim_at_6hr.py a 2nd time...

**Comment by goord** [comment]
This is typical strange python behavior. But it should not appear again after commit 3f416651ab1f551a99a99bddeb87487507e9479a
