### ISSUE TITLE
Problem processing ps for Primavera

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#82]
When trying to process the 6 hr frequency I get the following error related to sfc pressure.

```
INFO:postproc:Post-processing target ps in table Amon from file /nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/6hr/ICMSHps11+198001 with cdo command -sp2gpl -monmean -selmon,1 -selcode,134
INFO:postproc:Post-processing target ps in table CFday from file /nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/6hr/ICMSHps11+198001 with cdo command -sp2gpl -daymean -selmon,1 -selcode,134
INFO:ifs2cmor:Post-processed batch of 2 tasks.
INFO:ifs2cmor:Cmorizing 2 IFS tasks...
Error in calling operator griddes with:
>>> cdo griddes /nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/198001/ps_Amon.nc<<<
cdo griddes: Open failed on >/nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/198001/ps_Amon.nc<
Unsupported file structure

Traceback (most recent call last):
  File "./ece2cmor.py", line 88, in <module>
    main(sys.argv[1:])
  File "./ece2cmor.py", line 83, in main
    maxsizegb = args.tmpsize)
  File "/home/sm_wyser/ece2cmor3/ece2cmorlib.py", line 135, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks,cleanup = cleanup)
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 135, in execute
    cmorize(oldsptasks)
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 329, in cmorize
    gridid = create_grid_from_grib(getattr(tasks[0],"path"))
  File "/home/sm_wyser/ece2cmor3/ifs2cmor.py", line 665, in create_grid_from_grib
    griddescr = command.get_griddes(filepath)
  File "/home/sm_wyser/ece2cmor3/cdoapi.py", line 144, in get_griddes
    infolist = self.app.griddes(input = ifile)
  File "/home/sm_wyser/.conda/envs/ece2cmor3/lib/python2.7/site-packages/cdo.py", line 216, in get
    raise CDOException(**retvals)
cdo.CDOException: (returncode:1) cdo griddes: Open failed on >/nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/198001/ps_Amon.nc<
Unsupported file structure
```

The file ``/nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/198001/ps_Amon.nc`` hasn't been created yet ``/nobackup/rossby20/rossby/joint_exp/primavera/sm_wyser/ece2cmor3-tmp/6hr/ICMSHps11+198001``  exists.

Any idea what's wrong?

**Comment by goord** [comment]
Hi Klaus, it looks like something went wrong with the filtering of the spectral grib file. Does this error occur in the first month of the first year of the output? Can you check whether cdo sinfo works on other spectral grib files in the 6hr folder after filtering?

**Comment by goord** [comment]
BTW I am working on a more robust way of filtering, without a separate script.

**Comment by klauswyser** [comment]
Yes, this error occurs in the first month of a run, and I just realized that I happend to save model levels instead of pressure levels in ICMSH+000000. My bad. I have tested with a later year and the error is gone. Closing the issue.
